name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Before build
        run: |
          sed -i 's/SimSun/Noto Serif CJK SC/; s/SimHei/Noto Sans CJK SC/; s/Consolas/FreeMono/' prelude.sty
      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make font-noto-cjk ttf-freefont
            make
      - name: After build
        run: |
          export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mv amathtour-en.pdf "amathtour-en-$GIT_HASH.pdf"
          mv amathtour-zh-cn.pdf "amathtour-zh-cn-$GIT_HASH.pdf"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: amathtour
          path: amathtour-*.pdf
